name: Run Feed Parser

on:
  workflow_dispatch:  # Adds manual trigger button

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz
          
      - name: Run parser
        run: |
          # Create output directory in the workspace instead of Desktop
          mkdir -p output
          # Modify the script to use the current directory
          sed -i 's|os.path.join(os.path.expanduser("~"), "Desktop")|"output"|g' feed-me.py
          python feed-me.py
          
      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: rss_webpage
          path: output/rss_webpage.html